// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFyfp6ciWqT63GJtasgwPiwpTdk-0Ygto',
    appId: '1:433607737949:web:19326975e1d105f68d43b4',
    messagingSenderId: '433607737949',
    projectId: 'mecore-ab466',
    authDomain: 'mecore-ab466.firebaseapp.com',
    storageBucket: 'mecore-ab466.firebasestorage.app',
    measurementId: 'G-BGBEBH0MQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU7-sD21hJXtMIKGyW1x2mbTGDn_gBz5M',
    appId: '1:433607737949:android:b7f0f34aa88559978d43b4',
    messagingSenderId: '433607737949',
    projectId: 'mecore-ab466',
    storageBucket: 'mecore-ab466.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqcOdyt-igVY1wC818jpNJaz7FVimpbTQ',
    appId: '1:433607737949:ios:201d5cfb1b23ca198d43b4',
    messagingSenderId: '433607737949',
    projectId: 'mecore-ab466',
    storageBucket: 'mecore-ab466.firebasestorage.app',
    iosBundleId: 'com.hashtagmood.mecore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqcOdyt-igVY1wC818jpNJaz7FVimpbTQ',
    appId: '1:433607737949:ios:201d5cfb1b23ca198d43b4',
    messagingSenderId: '433607737949',
    projectId: 'mecore-ab466',
    storageBucket: 'mecore-ab466.firebasestorage.app',
    iosBundleId: 'com.hashtagmood.mecore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFyfp6ciWqT63GJtasgwPiwpTdk-0Ygto',
    appId: '1:433607737949:web:3c0ad24d80f718758d43b4',
    messagingSenderId: '433607737949',
    projectId: 'mecore-ab466',
    authDomain: 'mecore-ab466.firebaseapp.com',
    storageBucket: 'mecore-ab466.firebasestorage.app',
    measurementId: 'G-6PLPTTLHM1',
  );

}